- name: ping playbook
  hosts: localhost
  vars:
    age: "34"
    nam: "sai"
  tasks: 
  - name: ping the server
    vars:
      nam: "ram"
    ansible.builtin.debug:
      msg: "Hi my name is {{nam}}"